# Generated by Django 3.1.3 on 2020-11-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rant_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rantpost',
            name='feeling_level',
            field=models.CharField(choices=[('Sad', 'Sad'), ('T', 'Test'), ('N', 'Neutral')], default='N', max_length=3),
        ),
    ]
