# Generated by Django 3.1.3 on 2020-11-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rant_post', '0002_rantpost_feeling_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rantpost',
            name='feeling_level',
            field=models.CharField(choices=[('VS', 'Very Sad'), ('N', 'Neutral'), ('P', 'Pissed'), ('EP', 'Extremely Pissed'), ('FF', 'Fucking Furious')], default='N', max_length=3),
        ),
    ]
