# Generated by Django 3.1.3 on 2020-11-07 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rant_post', '0003_auto_20201108_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rantpost',
            name='updated_on',
        ),
    ]
