# Generated by Django 3.1.3 on 2020-11-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rant_post', '0005_auto_20201108_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rantpost',
            old_name='user',
            new_name='author',
        ),
    ]
