# Generated by Django 3.1.3 on 2020-11-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rant_post', '0006_auto_20201108_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rantpost',
            options={'ordering': ['-created_on']},
        ),
    ]
