# Generated by Django 3.1.3 on 2020-11-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rant_post', '0008_auto_20201129_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rantpost',
            name='upvote_count',
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
