# Generated by Django 3.1.3 on 2021-01-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rant_post', '0010_postreact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postreact',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postreact',
            old_name='user_id',
            new_name='user',
        ),
    ]
