# Generated by Django 3.1.3 on 2021-01-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rant_post', '0011_auto_20210106_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rantpost',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
