# Generated by Django 3.1.3 on 2021-02-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rant_post', '0014_categoryoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoption',
            name='id',
        ),
        migrations.AlterField(
            model_name='categoryoption',
            name='category_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
