# Generated by Django 3.1.3 on 2021-02-07 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rant_post', '0015_auto_20210207_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='rantpost',
            name='category',
            field=models.ForeignKey(default='General', on_delete=django.db.models.deletion.SET_DEFAULT, to='rant_post.categoryoption'),
        ),
    ]
