# Generated by Django 3.1.3 on 2021-02-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rant_post', '0016_rantpost_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rantpost',
            name='category',
        ),
        migrations.AddField(
            model_name='rantpost',
            name='category',
            field=models.ManyToManyField(default='General', to='rant_post.CategoryOption'),
        ),
    ]
