# Generated by Django 3.1.3 on 2021-02-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rant_post', '0017_auto_20210207_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rantpost',
            name='category',
            field=models.ManyToManyField(default=['General'], to='rant_post.CategoryOption'),
        ),
    ]
