# Generated by Django 3.1.3 on 2021-02-07 13:03

from django.db import migrations, models
import rant_post.models


class Migration(migrations.Migration):

    dependencies = [
        ('rant_post', '0018_auto_20210207_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rantpost',
            name='category',
            field=models.ManyToManyField(default=rant_post.models.default_category, to='rant_post.CategoryOption'),
        ),
    ]
