# Generated by Django 3.1.3 on 2021-02-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rant_post', '0019_auto_20210207_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rantpost',
            old_name='category',
            new_name='category_list',
        ),
    ]
